'use client';
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "./store";
import Head from "next/head";
import AdminSidebar from "./components/adminSidebar";
import { usePathname } from "next/navigation";
import UserNavbar from "./components/userNavbar";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  const currentPath = usePathname();
  const isAdmin = currentPath.startsWith('/admin');
  const isAuthPage = ["/", "/admin/login-admin", "/user/login-user", "/user/register-user"].includes(currentPath);

  return (
    <html lang="en">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body className={inter.className}>
        <Provider store={store}>
          <div className={`h-screen bg-[#E3EDF9] ${isAdmin ? 'flex' : ''}`}>
            {isAuthPage ? (
              children
            ) : (
              <>
                {isAdmin ? <AdminSidebar /> : <UserNavbar />}
                <div className="flex-1 overflow-auto">{children}</div>
              </>
            )}
          </div>
        </Provider>
      </body>
    </html>
  );
}
